
services:
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/project
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php81-service
            - mysql8-service
        networks:
            - nginx-php81-mysql8
    php81-service:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: php81-container
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/project

        networks:
            - nginx-php81-mysql8
    mysql8-service:
        image: mysql:8
        container_name: mysql8-container
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"

        networks:
            - nginx-php81-mysql8
networks:
    nginx-php81-mysql8: {}


volumes:
    mysql_data: